<a href="https://colab.research.google.com/github/manishchan/ScrapingData/blob/master/Flipkart_Product_Price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
item = input('Enter the item name: ')

Enter the item name: macbook

In [3]:
page_name = []
page_price = []
page_rating = []
page_org_price = []

page_num = input('Enter the number of pages: ')
for i in range(1,int(page_num)+1):
  url = 'https://www.flipkart.com/search?q='+item+'&page='+str(i)

  req = requests.get(url)
  content = BeautifulSoup(req.content, 'html.parser')
  
  name = content.find_all('div',{'class':'_4rR01T'})
  price = content.find_all('div',{'class':'_30jeq3 _1_WHN1'})
  rating = content.find_all('div',{'class':'_3LWZlK'})
  org_price = content.find_all('div',{'class':'_3I9_wc _27UcVY'})

  for i in name:
    page_name.append(i.text)
  for i in price:
    page_price.append(i.text)
  for i in rating:
    page_rating.append(i.text)
  for i in org_price:
    page_org_price.append(i.text)

Enter the number of pages: 50

In [4]:
data = {'Name':page_name, 'Price':page_price, 'Rating':page_rating, 'Org_Price':page_org_price}

df = pd.DataFrame.from_dict(data, orient='index').transpose()

df = df.dropna()

In [5]:
df['Price'] = df['Price'].replace({'₹':'',',':'','â‚¹':''}, regex=True)
df['Org_Price'] = df['Org_Price'].replace({'₹':'',',':'','â‚¹':''}, regex=True)

df['Price'] = pd.to_numeric(df['Price'])
df['Org_Price'] = pd.to_numeric(df['Org_Price'])

In [6]:
df.sort_values(by='Price', ascending=False, ignore_index=True)

,Name,Price,Rating,Org_Price
0,APPLE 2021 Macbook Pro M1 Pro - (16 GB/1 TB SS...,245990,4.7,162900
1,APPLE 2021 Macbook Pro M1 Pro - (16 GB/512 GB ...,227990,4.7,179900
2,APPLE MacBook Air M1 - (16 GB/512 GB SSD/Mac O...,132900,4.7,239900
3,APPLE MacBook Air M1 - (16 GB/512 GB SSD/Mac O...,132900,4.7,239900
4,APPLE 2020 Macbook Air M1 - (8 GB/512 GB SSD/M...,117900,4.6,84900
5,APPLE MacBook Air M1 - (16 GB/256 GB SSD/Mac O...,112900,4.7,110900
6,APPLE MacBook Air M1 - (16 GB/256 GB SSD/Mac O...,112900,4.7,239900
7,APPLE MacBook Air M1 - (8 GB/512 GB SSD/Mac OS...,110900,4.7,259900
8,APPLE MacBook Air M1 - (8 GB/512 GB SSD/Mac OS...,109990,4.7,142900
9,APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/M...,94990,4.7,99900
10,APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/M...,94990,4.7,99900
11,APPLE MacBook Air Core i5 5th Gen - (8 GB/128 ...,73490,4.7,329900

In [9]:
df[df['Name'].str.contains('16 GB')].sort_values(by='Price', ignore_index=True)

                                                Name   Price Rating  Org_Price
0  APPLE MacBook Air M1 - (16 GB/256 GB SSD/Mac O...  112900    4.7     110900
1  APPLE MacBook Air M1 - (16 GB/256 GB SSD/Mac O...  112900    4.7     239900
2  APPLE MacBook Air M1 - (16 GB/512 GB SSD/Mac O...  132900    4.7     239900
3  APPLE MacBook Air M1 - (16 GB/512 GB SSD/Mac O...  132900    4.7     239900
4  APPLE 2021 Macbook Pro M1 Pro - (16 GB/512 GB ...  227990    4.7     179900
5  APPLE 2021 Macbook Pro M1 Pro - (16 GB/1 TB SS...  245990    4.7     162900

In [8]:
#df.to_csv('flip_mcair.csv', index=False)